language: objective-c  
osx_image: xcode7.3
xcode_project: MulticastDelegateDemo.xcodeproj 
xcode_scheme: MulticastDelegateDemo
xcode_sdk: iphonesimulator9.3
notifications:
  email: false
script: set -o pipefail && xcodebuild test -project MulticastDelegateDemo.xcodeproj -scheme MulticastDelegateDemo -sdk iphonesimulator9.3 | xcpretty
