language: objective-c  
osx_image: xcode7.3
xcode_project: MulticastDelegateDemo.xcodeproj 
xcode_scheme: MulticastDelegateDemo
xcode_sdk: iphonesimulator9.3
notifications:
  email: false
before_install:
 - brew uninstall xctool && brew install --HEAD xctool
